OPENAI_API_KEY="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"
SF_USER='SF USER NAME'
SF_PASSWORD='SF PASSWORD FOR ABOVE USER'
SF_ACCOUNT='SF ACCOUNT IDENTIFIER'
SF_WAREHOUSE='SF WAREHOUSE'
SF_DATABASE = 'SF DATABASE'
SF_SCHEMA = 'SF SCHEMA'
SF_ROLE='ACCOUNTADMIN'
